name: nuget-artifacts

on:
  workflow_run:
    workflows: [build-artifacts]
    types: [completed]
  workflow_dispatch:

jobs:
  pack:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: Itexoft/DevOpsKit/.github/workflows/nuget-package-publish.yml@master
    secrets: inherit
    with:
      project_name: psychec
      csproj_path: nuget/PsycheC.Native.csproj
      build_workflow: build-artifacts
      extra_paths: docs
      publish_branch: master
      publish: false