name: solver-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd solver
      run: cd solver
    - name: setup
      run: stack setup
    - name: build
      run: stack build
